
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Apr 06 21:19:00 CEST 2024
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int ID_READ = 36;
  public static final int LITERAL_ENTERO = 49;
  public static final int TERMINACION = 2;
  public static final int PARENTESIS_CIERRE = 15;
  public static final int PUNTO_Y_COMA = 4;
  public static final int LITERAL_REAL = 51;
  public static final int ID_PROC = 33;
  public static final int ID_WRITE = 37;
  public static final int RESTA = 25;
  public static final int REFERENCIA = 42;
  public static final int ID_INT = 17;
  public static final int ID_OR = 44;
  public static final int IDENTIFICADOR = 50;
  public static final int IGUAL = 10;
  public static final int CORCHETE_CIERRE = 12;
  public static final int ID_AND = 43;
  public static final int ID_NOT = 29;
  public static final int ID_IF = 31;
  public static final int SUMA = 24;
  public static final int INI_NOMBRE = 30;
  public static final int LITERAL_CADENA = 52;
  public static final int EOF = 0;
  public static final int TRUE = 45;
  public static final int CORCHETE_APERTURA = 11;
  public static final int ID_STRING = 20;
  public static final int error = 1;
  public static final int COMA = 16;
  public static final int MODULO = 28;
  public static final int MENOR = 5;
  public static final int ID_STRUCT = 21;
  public static final int ID_NEW = 39;
  public static final int ID_TYPE = 34;
  public static final int DESIGUAL = 9;
  public static final int ID_BOOL = 19;
  public static final int ASIGNACION = 3;
  public static final int ID_CALL = 35;
  public static final int MAYOR = 6;
  public static final int ID_WHILE = 38;
  public static final int INDIRECCION = 48;
  public static final int ID_NL = 41;
  public static final int PUNTO = 13;
  public static final int LLAVE_APERTURA = 22;
  public static final int MAYOR_IGUAL = 8;
  public static final int LLAVE_CIERRE = 23;
  public static final int ID_NULL = 47;
  public static final int PARENTESIS_APERTURA = 14;
  public static final int MENOR_IGUAL = 7;
  public static final int FALSE = 46;
  public static final int ID_DELETE = 40;
  public static final int DIVISION = 27;
  public static final int ID_REAL = 18;
  public static final int MULTIPLICACION = 26;
  public static final int ID_ELSE = 32;
}

