
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Apr 06 23:58:35 CEST 2024
//----------------------------------------------------

package c_ast_ascendente;

import java_cup.runtime.*;
import alex.AnalizadorLexicoTiny;
import alex.UnidadLexica;
import errors.GestionErroresTiny;
import asint.ClaseSemantica;
import asint.SintaxisAbstracta.*;
import c_ast_ascendente.UnidadLexica.StringLocalizado;
import java_cup.runtime.ComplexSymbolFactory.Location;

/** CUP v0.11b beta 20140220 generated parser.
  * @version Sat Apr 06 23:58:35 CEST 2024
  */
public class ConstructorASTs extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ConstructorASTs() {super();}

  /** Constructor which sets the default scanner. */
  public ConstructorASTs(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ConstructorASTs(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\131\000\002\002\003\000\002\002\004\000\002\003" +
    "\006\000\002\004\004\000\002\004\002\000\002\005\005" +
    "\000\002\005\003\000\002\006\006\000\002\006\005\000" +
    "\002\006\004\000\002\015\005\000\002\016\003\000\002" +
    "\016\002\000\002\017\005\000\002\017\003\000\002\022" +
    "\005\000\002\022\004\000\002\007\003\000\002\010\006" +
    "\000\002\010\003\000\002\011\004\000\002\011\003\000" +
    "\002\012\003\000\002\012\003\000\002\012\003\000\002" +
    "\012\003\000\002\012\003\000\002\012\006\000\002\036" +
    "\005\000\002\036\003\000\002\020\004\000\002\013\003" +
    "\000\002\013\002\000\002\014\005\000\002\014\003\000" +
    "\002\021\004\000\002\021\005\000\002\021\003\000\002" +
    "\021\004\000\002\021\004\000\002\021\004\000\002\021" +
    "\004\000\002\021\005\000\002\021\007\000\002\021\005" +
    "\000\002\021\003\000\002\037\005\000\002\040\003\000" +
    "\002\040\002\000\002\041\005\000\002\041\003\000\002" +
    "\042\003\000\002\023\005\000\002\023\003\000\002\024" +
    "\005\000\002\024\003\000\002\025\005\000\002\025\005" +
    "\000\002\025\003\000\002\026\005\000\002\026\005\000" +
    "\002\026\003\000\002\027\005\000\002\027\003\000\002" +
    "\030\004\000\002\030\003\000\002\031\006\000\002\031" +
    "\005\000\002\031\004\000\002\031\003\000\002\032\003" +
    "\000\002\032\003\000\002\032\003\000\002\032\003\000" +
    "\002\032\003\000\002\032\003\000\002\032\003\000\002" +
    "\032\005\000\002\033\003\000\002\033\003\000\002\033" +
    "\003\000\002\033\003\000\002\033\003\000\002\033\003" +
    "\000\002\034\003\000\002\034\003\000\002\034\003\000" +
    "\002\035\003\000\002\035\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\214\000\004\030\006\001\002\000\004\002\216\001" +
    "\002\000\004\002\001\001\002\000\052\023\023\024\026" +
    "\025\012\026\010\027\007\030\ufffd\031\ufffd\040\ufffd\041" +
    "\ufffd\043\022\044\024\045\ufffd\046\ufffd\047\ufffd\050\ufffd" +
    "\051\ufffd\052\ufffd\053\ufffd\062\013\064\025\001\002\000" +
    "\004\030\206\001\002\000\010\015\uffe8\054\uffe8\064\uffe8" +
    "\001\002\000\030\030\006\031\uffe1\040\073\041\060\045" +
    "\061\046\063\047\067\050\071\051\070\052\066\053\057" +
    "\001\002\000\010\015\uffe9\054\uffe9\064\uffe9\001\002\000" +
    "\020\023\023\024\026\025\012\026\010\027\007\062\013" +
    "\064\025\001\002\000\010\015\uffec\054\uffec\064\uffec\001" +
    "\002\000\010\015\uffee\054\uffee\064\uffee\001\002\000\006" +
    "\004\ufffb\006\ufffb\001\002\000\010\015\053\054\ufff0\064" +
    "\ufff0\001\002\000\006\004\050\006\051\001\002\000\004" +
    "\064\047\001\002\000\004\064\031\001\002\000\010\015" +
    "\uffeb\054\uffeb\064\uffeb\001\002\000\020\023\023\024\026" +
    "\025\012\026\010\027\007\062\013\064\025\001\002\000" +
    "\010\015\uffe7\054\uffe7\064\uffe7\001\002\000\010\015\uffea" +
    "\054\uffea\064\uffea\001\002\000\004\064\030\001\002\000" +
    "\006\004\ufff9\006\ufff9\001\002\000\004\020\032\001\002" +
    "\000\022\021\ufff5\023\023\024\026\025\012\026\010\027" +
    "\007\062\013\064\025\001\002\000\004\030\006\001\002" +
    "\000\006\004\ufffa\006\ufffa\001\002\000\006\021\ufff3\022" +
    "\ufff3\001\002\000\006\021\ufff6\022\045\001\002\000\006" +
    "\054\042\064\043\001\002\000\004\021\041\001\002\000" +
    "\004\030\ufff7\001\002\000\004\064\044\001\002\000\006" +
    "\021\ufff1\022\ufff1\001\002\000\006\021\ufff2\022\ufff2\001" +
    "\002\000\020\023\023\024\026\025\012\026\010\027\007" +
    "\062\013\064\025\001\002\000\006\021\ufff4\022\ufff4\001" +
    "\002\000\006\004\ufff8\006\ufff8\001\002\000\030\030\ufffe" +
    "\031\ufffe\040\ufffe\041\ufffe\045\ufffe\046\ufffe\047\ufffe\050" +
    "\ufffe\051\ufffe\052\ufffe\053\ufffe\001\002\000\024\023\023" +
    "\024\026\025\012\026\010\027\007\043\022\044\024\062" +
    "\013\064\025\001\002\000\006\004\ufffc\006\ufffc\001\002" +
    "\000\004\063\054\001\002\000\004\016\055\001\002\000" +
    "\010\015\uffef\054\uffef\064\uffef\001\002\000\010\015\uffed" +
    "\054\uffed\064\uffed\001\002\000\006\006\uffdc\031\uffdc\001" +
    "\002\000\026\020\100\033\117\037\074\057\077\060\112" +
    "\061\115\063\111\064\113\065\110\066\116\001\002\000" +
    "\004\064\171\001\002\000\006\006\uffd4\031\uffd4\001\002" +
    "\000\026\020\100\033\117\037\074\057\077\060\112\061" +
    "\115\063\111\064\113\065\110\066\116\001\002\000\004" +
    "\031\167\001\002\000\006\006\uffdf\031\uffdf\001\002\000" +
    "\026\020\100\033\117\037\074\057\077\060\112\061\115" +
    "\063\111\064\113\065\110\066\116\001\002\000\026\020" +
    "\100\033\117\037\074\057\077\060\112\061\115\063\111" +
    "\064\113\065\110\066\116\001\002\000\026\020\100\033" +
    "\117\037\074\057\077\060\112\061\115\063\111\064\113" +
    "\065\110\066\116\001\002\000\026\020\100\033\117\037" +
    "\074\057\077\060\112\061\115\063\111\064\113\065\110" +
    "\066\116\001\002\000\006\006\160\031\uffe2\001\002\000" +
    "\026\020\100\033\117\037\074\057\077\060\112\061\115" +
    "\063\111\064\113\065\110\066\116\001\002\000\026\020" +
    "\uffa9\033\uffa9\037\uffa9\057\uffa9\060\uffa9\061\uffa9\063\uffa9" +
    "\064\uffa9\065\uffa9\066\uffa9\001\002\000\006\006\uffde\031" +
    "\uffde\001\002\000\060\005\uffbc\006\uffbc\007\uffbc\010\uffbc" +
    "\011\uffbc\012\uffbc\013\uffbc\014\uffbc\015\uffbc\016\uffbc\017" +
    "\uffbc\021\uffbc\022\uffbc\030\uffbc\031\uffbc\032\uffbc\033\uffbc" +
    "\034\uffbc\035\uffbc\036\uffbc\055\uffbc\056\uffbc\062\uffbc\001" +
    "\002\000\060\005\uffb7\006\uffb7\007\uffb7\010\uffb7\011\uffb7" +
    "\012\uffb7\013\uffb7\014\uffb7\015\uffb7\016\uffb7\017\uffb7\021" +
    "\uffb7\022\uffb7\030\uffb7\031\uffb7\032\uffb7\033\uffb7\034\uffb7" +
    "\035\uffb7\036\uffb7\055\uffb7\056\uffb7\062\uffb7\001\002\000" +
    "\026\020\100\033\117\037\074\057\077\060\112\061\115" +
    "\063\111\064\113\065\110\066\116\001\002\000\060\005" +
    "\uffc0\006\uffc0\007\uffc0\010\uffc0\011\uffc0\012\uffc0\013\uffc0" +
    "\014\uffc0\015\151\016\uffc0\017\150\021\uffc0\022\uffc0\030" +
    "\uffc0\031\uffc0\032\uffc0\033\uffc0\034\uffc0\035\uffc0\036\uffc0" +
    "\055\uffc0\056\uffc0\062\152\001\002\000\052\005\uffc2\006" +
    "\uffc2\007\uffc2\010\uffc2\011\uffc2\012\uffc2\013\uffc2\014\uffc2" +
    "\016\uffc2\021\uffc2\022\uffc2\030\uffc2\031\uffc2\032\uffc2\033" +
    "\uffc2\034\uffc2\035\uffc2\036\uffc2\055\uffc2\056\uffc2\001\002" +
    "\000\052\005\uffc4\006\uffc4\007\uffc4\010\uffc4\011\uffc4\012" +
    "\uffc4\013\uffc4\014\uffc4\016\uffc4\021\uffc4\022\uffc4\030\uffc4" +
    "\031\uffc4\032\uffc4\033\uffc4\034\140\035\144\036\142\055" +
    "\137\056\143\001\002\000\040\005\uffc7\006\uffc7\007\uffc7" +
    "\010\uffc7\011\uffc7\012\uffc7\013\uffc7\014\uffc7\016\uffc7\021" +
    "\uffc7\022\uffc7\030\uffc7\031\uffc7\032\uffc7\033\135\001\002" +
    "\000\036\005\uffca\006\uffca\007\uffca\010\uffca\011\uffca\012" +
    "\uffca\013\uffca\014\uffca\016\uffca\021\uffca\022\uffca\030\uffca" +
    "\031\uffca\032\132\001\002\000\034\005\121\006\uffcc\007" +
    "\125\010\126\011\127\012\130\013\122\014\124\016\uffcc" +
    "\021\uffcc\022\uffcc\030\uffcc\031\uffcc\001\002\000\014\006" +
    "\uffce\021\uffce\022\uffce\030\uffce\031\uffce\001\002\000\060" +
    "\005\uffbb\006\uffbb\007\uffbb\010\uffbb\011\uffbb\012\uffbb\013" +
    "\uffbb\014\uffbb\015\uffbb\016\uffbb\017\uffbb\021\uffbb\022\uffbb" +
    "\030\uffbb\031\uffbb\032\uffbb\033\uffbb\034\uffbb\035\uffbb\036" +
    "\uffbb\055\uffbb\056\uffbb\062\uffbb\001\002\000\060\005\uffba" +
    "\006\uffba\007\uffba\010\uffba\011\uffba\012\uffba\013\uffba\014" +
    "\uffba\015\uffba\016\uffba\017\uffba\021\uffba\022\uffba\030\uffba" +
    "\031\uffba\032\uffba\033\uffba\034\uffba\035\uffba\036\uffba\055" +
    "\uffba\056\uffba\062\uffba\001\002\000\060\005\uffb6\006\uffb6" +
    "\007\uffb6\010\uffb6\011\uffb6\012\uffb6\013\uffb6\014\uffb6\015" +
    "\uffb6\016\uffb6\017\uffb6\021\uffb6\022\uffb6\030\uffb6\031\uffb6" +
    "\032\uffb6\033\uffb6\034\uffb6\035\uffb6\036\uffb6\055\uffb6\056" +
    "\uffb6\062\uffb6\001\002\000\060\005\uffb9\006\uffb9\007\uffb9" +
    "\010\uffb9\011\uffb9\012\uffb9\013\uffb9\014\uffb9\015\uffb9\016" +
    "\uffb9\017\uffb9\021\uffb9\022\uffb9\030\uffb9\031\uffb9\032\uffb9" +
    "\033\uffb9\034\uffb9\035\uffb9\036\uffb9\055\uffb9\056\uffb9\062" +
    "\uffb9\001\002\000\026\020\100\033\117\037\074\057\077" +
    "\060\112\061\115\063\111\064\113\065\110\066\116\001" +
    "\002\000\060\005\uffb5\006\uffb5\007\uffb5\010\uffb5\011\uffb5" +
    "\012\uffb5\013\uffb5\014\uffb5\015\uffb5\016\uffb5\017\uffb5\021" +
    "\uffb5\022\uffb5\030\uffb5\031\uffb5\032\uffb5\033\uffb5\034\uffb5" +
    "\035\uffb5\036\uffb5\055\uffb5\056\uffb5\062\uffb5\001\002\000" +
    "\060\005\uffb8\006\uffb8\007\uffb8\010\uffb8\011\uffb8\012\uffb8" +
    "\013\uffb8\014\uffb8\015\uffb8\016\uffb8\017\uffb8\021\uffb8\022" +
    "\uffb8\030\uffb8\031\uffb8\032\uffb8\033\uffb8\034\uffb8\035\uffb8" +
    "\036\uffb8\055\uffb8\056\uffb8\062\uffb8\001\002\000\026\020" +
    "\uffaa\033\uffaa\037\uffaa\057\uffaa\060\uffaa\061\uffaa\063\uffaa" +
    "\064\uffaa\065\uffaa\066\uffaa\001\002\000\052\005\uffc1\006" +
    "\uffc1\007\uffc1\010\uffc1\011\uffc1\012\uffc1\013\uffc1\014\uffc1" +
    "\016\uffc1\021\uffc1\022\uffc1\030\uffc1\031\uffc1\032\uffc1\033" +
    "\uffc1\034\uffc1\035\uffc1\036\uffc1\055\uffc1\056\uffc1\001\002" +
    "\000\026\020\100\033\117\037\074\057\077\060\112\061" +
    "\115\063\111\064\113\065\110\066\116\001\002\000\026" +
    "\020\uffaf\033\uffaf\037\uffaf\057\uffaf\060\uffaf\061\uffaf\063" +
    "\uffaf\064\uffaf\065\uffaf\066\uffaf\001\002\000\026\020\100" +
    "\033\117\037\074\057\077\060\112\061\115\063\111\064" +
    "\113\065\110\066\116\001\002\000\026\020\uffae\033\uffae" +
    "\037\uffae\057\uffae\060\uffae\061\uffae\063\uffae\064\uffae\065" +
    "\uffae\066\uffae\001\002\000\026\020\uffb3\033\uffb3\037\uffb3" +
    "\057\uffb3\060\uffb3\061\uffb3\063\uffb3\064\uffb3\065\uffb3\066" +
    "\uffb3\001\002\000\026\020\uffb2\033\uffb2\037\uffb2\057\uffb2" +
    "\060\uffb2\061\uffb2\063\uffb2\064\uffb2\065\uffb2\066\uffb2\001" +
    "\002\000\026\020\uffb1\033\uffb1\037\uffb1\057\uffb1\060\uffb1" +
    "\061\uffb1\063\uffb1\064\uffb1\065\uffb1\066\uffb1\001\002\000" +
    "\026\020\uffb0\033\uffb0\037\uffb0\057\uffb0\060\uffb0\061\uffb0" +
    "\063\uffb0\064\uffb0\065\uffb0\066\uffb0\001\002\000\036\005" +
    "\uffcb\006\uffcb\007\uffcb\010\uffcb\011\uffcb\012\uffcb\013\uffcb" +
    "\014\uffcb\016\uffcb\021\uffcb\022\uffcb\030\uffcb\031\uffcb\032" +
    "\132\001\002\000\026\020\100\033\117\037\074\057\077" +
    "\060\112\061\115\063\111\064\113\065\110\066\116\001" +
    "\002\000\036\005\uffc9\006\uffc9\007\uffc9\010\uffc9\011\uffc9" +
    "\012\uffc9\013\uffc9\014\uffc9\016\uffc9\021\uffc9\022\uffc9\030" +
    "\uffc9\031\uffc9\032\uffc9\001\002\000\016\006\uffcd\016\uffcd" +
    "\021\uffcd\022\uffcd\030\uffcd\031\uffcd\001\002\000\026\020" +
    "\100\033\117\037\074\057\077\060\112\061\115\063\111" +
    "\064\113\065\110\066\116\001\002\000\036\005\uffc8\006" +
    "\uffc8\007\uffc8\010\uffc8\011\uffc8\012\uffc8\013\uffc8\014\uffc8" +
    "\016\uffc8\021\uffc8\022\uffc8\030\uffc8\031\uffc8\032\uffc8\001" +
    "\002\000\026\020\100\033\117\037\074\057\077\060\112" +
    "\061\115\063\111\064\113\065\110\066\116\001\002\000" +
    "\026\020\uffad\033\uffad\037\uffad\057\uffad\060\uffad\061\uffad" +
    "\063\uffad\064\uffad\065\uffad\066\uffad\001\002\000\026\020" +
    "\100\033\117\037\074\057\077\060\112\061\115\063\111" +
    "\064\113\065\110\066\116\001\002\000\026\020\uffab\033" +
    "\uffab\037\uffab\057\uffab\060\uffab\061\uffab\063\uffab\064\uffab" +
    "\065\uffab\066\uffab\001\002\000\026\020\100\033\117\037" +
    "\074\057\077\060\112\061\115\063\111\064\113\065\110" +
    "\066\116\001\002\000\026\020\uffac\033\uffac\037\uffac\057" +
    "\uffac\060\uffac\061\uffac\063\uffac\064\uffac\065\uffac\066\uffac" +
    "\001\002\000\046\005\uffc5\006\uffc5\007\uffc5\010\uffc5\011" +
    "\uffc5\012\uffc5\013\uffc5\014\uffc5\016\uffc5\021\uffc5\022\uffc5" +
    "\030\uffc5\031\uffc5\032\uffc5\033\uffc5\034\140\035\144\036" +
    "\142\001\002\000\052\005\uffc3\006\uffc3\007\uffc3\010\uffc3" +
    "\011\uffc3\012\uffc3\013\uffc3\014\uffc3\016\uffc3\021\uffc3\022" +
    "\uffc3\030\uffc3\031\uffc3\032\uffc3\033\uffc3\034\uffc3\035\uffc3" +
    "\036\uffc3\055\uffc3\056\uffc3\001\002\000\040\005\uffc6\006" +
    "\uffc6\007\uffc6\010\uffc6\011\uffc6\012\uffc6\013\uffc6\014\uffc6" +
    "\016\uffc6\021\uffc6\022\uffc6\030\uffc6\031\uffc6\032\uffc6\033" +
    "\uffc6\001\002\000\004\064\155\001\002\000\026\020\100" +
    "\033\117\037\074\057\077\060\112\061\115\063\111\064" +
    "\113\065\110\066\116\001\002\000\060\005\uffbd\006\uffbd" +
    "\007\uffbd\010\uffbd\011\uffbd\012\uffbd\013\uffbd\014\uffbd\015" +
    "\uffbd\016\uffbd\017\uffbd\021\uffbd\022\uffbd\030\uffbd\031\uffbd" +
    "\032\uffbd\033\uffbd\034\uffbd\035\uffbd\036\uffbd\055\uffbd\056" +
    "\uffbd\062\uffbd\001\002\000\004\016\154\001\002\000\060" +
    "\005\uffbf\006\uffbf\007\uffbf\010\uffbf\011\uffbf\012\uffbf\013" +
    "\uffbf\014\uffbf\015\uffbf\016\uffbf\017\uffbf\021\uffbf\022\uffbf" +
    "\030\uffbf\031\uffbf\032\uffbf\033\uffbf\034\uffbf\035\uffbf\036" +
    "\uffbf\055\uffbf\056\uffbf\062\uffbf\001\002\000\060\005\uffbe" +
    "\006\uffbe\007\uffbe\010\uffbe\011\uffbe\012\uffbe\013\uffbe\014" +
    "\uffbe\015\uffbe\016\uffbe\017\uffbe\021\uffbe\022\uffbe\030\uffbe" +
    "\031\uffbe\032\uffbe\033\uffbe\034\uffbe\035\uffbe\036\uffbe\055" +
    "\uffbe\056\uffbe\062\uffbe\001\002\000\004\021\157\001\002" +
    "\000\060\005\uffb4\006\uffb4\007\uffb4\010\uffb4\011\uffb4\012" +
    "\uffb4\013\uffb4\014\uffb4\015\uffb4\016\uffb4\017\uffb4\021\uffb4" +
    "\022\uffb4\030\uffb4\031\uffb4\032\uffb4\033\uffb4\034\uffb4\035" +
    "\uffb4\036\uffb4\055\uffb4\056\uffb4\062\uffb4\001\002\000\026" +
    "\030\006\040\073\041\060\045\061\046\063\047\067\050" +
    "\071\051\070\052\066\053\057\001\002\000\006\006\uffe0" +
    "\031\uffe0\001\002\000\004\030\006\001\002\000\006\006" +
    "\uffd7\031\uffd7\001\002\000\006\006\uffdb\031\uffdb\001\002" +
    "\000\006\006\uffd9\031\uffd9\001\002\000\006\006\uffd8\031" +
    "\uffd8\001\002\000\014\002\uffff\004\uffff\006\uffff\031\uffff" +
    "\042\uffff\001\002\000\006\006\uffda\031\uffda\001\002\000" +
    "\004\020\172\001\002\000\030\020\100\021\uffd1\033\117" +
    "\037\074\057\077\060\112\061\115\063\111\064\113\065" +
    "\110\066\116\001\002\000\006\006\uffdd\031\uffdd\001\002" +
    "\000\006\021\uffcf\022\uffcf\001\002\000\004\021\201\001" +
    "\002\000\006\021\uffd2\022\177\001\002\000\026\020\100" +
    "\033\117\037\074\057\077\060\112\061\115\063\111\064" +
    "\113\065\110\066\116\001\002\000\006\021\uffd0\022\uffd0" +
    "\001\002\000\006\006\uffd3\031\uffd3\001\002\000\004\030" +
    "\006\001\002\000\010\006\uffd5\031\uffd5\042\204\001\002" +
    "\000\004\030\006\001\002\000\006\006\uffd6\031\uffd6\001" +
    "\002\000\020\023\023\024\026\025\012\026\010\027\007" +
    "\062\013\064\025\001\002\000\004\064\215\001\002\000" +
    "\006\022\212\031\213\001\002\000\006\022\uffe4\031\uffe4" +
    "\001\002\000\020\023\023\024\026\025\012\026\010\027" +
    "\007\062\013\064\025\001\002\000\010\015\uffe6\054\uffe6" +
    "\064\uffe6\001\002\000\006\022\uffe5\031\uffe5\001\002\000" +
    "\006\022\uffe3\031\uffe3\001\002\000\004\002\000\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\214\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\020\004\010\005\017\006\015" +
    "\007\020\010\016\011\014\012\013\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\003\061\013\063\014\071" +
    "\021\064\001\001\000\002\001\001\000\006\011\055\012" +
    "\013\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\007\026" +
    "\010\016\011\014\012\013\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\015\032\001\001\000\020\007\036\010\016\011\014\012" +
    "\013\016\037\017\035\022\034\001\001\000\004\003\033" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\007\036\010\016\011\014\012\013\022\045\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\006\051\007\020\010\016\011\014\012\013\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\026" +
    "\023\106\024\105\025\104\026\103\027\102\030\101\031" +
    "\100\032\075\035\113\042\201\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\023\106\024\105\025\104\026" +
    "\103\027\102\030\101\031\100\032\075\035\113\042\167" +
    "\001\001\000\002\001\001\000\002\001\001\000\026\023" +
    "\106\024\105\025\104\026\103\027\102\030\101\031\100" +
    "\032\075\035\113\042\165\001\001\000\026\023\106\024" +
    "\105\025\104\026\103\027\102\030\101\031\100\032\075" +
    "\035\113\042\164\001\001\000\026\023\106\024\105\025" +
    "\104\026\103\027\102\030\101\031\100\032\075\035\113" +
    "\042\163\001\001\000\026\023\106\024\105\025\104\026" +
    "\103\027\102\030\101\031\100\032\075\035\113\042\161" +
    "\001\001\000\002\001\001\000\026\023\106\024\105\025" +
    "\104\026\103\027\102\030\101\031\100\032\075\035\113" +
    "\042\074\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\024\023\155\024\105" +
    "\025\104\026\103\027\102\030\101\031\100\032\075\035" +
    "\113\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\034\140\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\033\122\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\030\117\031\100\032\075\035\113\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\024\023\133\024\105\025\104\026\103\027\102" +
    "\030\101\031\100\032\075\035\113\001\001\000\002\001" +
    "\001\000\020\025\130\026\103\027\102\030\101\031\100" +
    "\032\075\035\113\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\026\132\027\102\030\101\031" +
    "\100\032\075\035\113\001\001\000\002\001\001\000\002" +
    "\001\001\000\016\026\135\027\102\030\101\031\100\032" +
    "\075\035\113\001\001\000\002\001\001\000\016\026\146" +
    "\027\102\030\101\031\100\032\075\035\113\001\001\000" +
    "\002\001\001\000\012\030\145\031\100\032\075\035\113" +
    "\001\001\000\002\001\001\000\014\027\144\030\101\031" +
    "\100\032\075\035\113\001\001\000\002\001\001\000\004" +
    "\034\140\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\024\023\152\024\105\025\104\026\103" +
    "\027\102\030\101\031\100\032\075\035\113\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\003" +
    "\061\021\160\001\001\000\002\001\001\000\004\003\162" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\037\172\001\001\000\032\023\106\024\105\025" +
    "\104\026\103\027\102\030\101\031\100\032\075\035\113" +
    "\040\174\041\175\042\173\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\026" +
    "\023\106\024\105\025\104\026\103\027\102\030\101\031" +
    "\100\032\075\035\113\042\177\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\003\202\001\001\000\002\001" +
    "\001\000\004\003\204\001\001\000\002\001\001\000\016" +
    "\007\206\010\016\011\014\012\013\020\210\036\207\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\007\206\010\016\011\014\012\013\020\213\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ConstructorASTs$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ConstructorASTs$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ConstructorASTs$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
 
   errores = new GestionErroresTiny();
   AnalizadorLexicoTiny alex = (AnalizadorLexicoTiny)getScanner();
   alex.fijaGestionErrores(errores);

    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 
  return getScanner().next_token(); 

    }

 
   private GestionErroresTiny errores;
   public void syntax_error(Symbol unidadLexica) {
     errores.errorSintactico((UnidadLexica)unidadLexica);
   }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ConstructorASTs$actions {


  ClaseSemantica sem = new ClaseSemantica();

  private final ConstructorASTs parser;

  /** Constructor */
  CUP$ConstructorASTs$actions(ConstructorASTs parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ConstructorASTs$do_action_part00000000(
    int                        CUP$ConstructorASTs$act_num,
    java_cup.runtime.lr_parser CUP$ConstructorASTs$parser,
    java.util.Stack            CUP$ConstructorASTs$stack,
    int                        CUP$ConstructorASTs$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ConstructorASTs$result;

      /* select the action based on the action number */
      switch (CUP$ConstructorASTs$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // programa ::= bloque 
            {
              Prog RESULT =null;
		Bloque bloq = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.prog(bloq); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("programa",0, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= programa EOF 
            {
              Object RESULT =null;
		Prog start_val = (Prog)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		RESULT = start_val;
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("$START",0, RESULT);
            }
          /* ACCEPT */
          CUP$ConstructorASTs$parser.done_parsing();
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // bloque ::= LLAVE_APERTURA declaraciones instrucciones LLAVE_CIERRE 
            {
              Bloque RESULT =null;
		Decs decs = (Decs)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		Instrs instrs = (Instrs)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		 RESULT = sem.bloq(decs, instrs); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("bloque",1, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // declaraciones ::= lista_declaraciones TERMINACION 
            {
              Decs RESULT =null;
		LDecs lista = (LDecs)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		 RESULT = sem.siDecs(lista); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("declaraciones",2, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // declaraciones ::= 
            {
              Decs RESULT =null;
		 RESULT = sem.noDecs(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("declaraciones",2, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lista_declaraciones ::= lista_declaraciones PUNTO_Y_COMA declaracion 
            {
              LDecs RESULT =null;
		LDecs lista = (LDecs)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		Dec dec = (Dec)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.muchasDecs(lista, dec); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("lista_declaraciones",3, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // lista_declaraciones ::= declaracion 
            {
              LDecs RESULT =null;
		Dec dec = (Dec)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.unaDec(dec); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("lista_declaraciones",3, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declaracion ::= ID_PROC IDENTIFICADOR parametros_formales bloque 
            {
              Dec RESULT =null;
		StringLocalizado id = (StringLocalizado)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		ParamForms params = (ParamForms)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		Bloque bloq = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = (Dec) sem.decProc(id.str(), params, bloq).ponFila(id.fila()).ponCol(id.col()); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("declaracion",4, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // declaracion ::= ID_TYPE tipo IDENTIFICADOR 
            {
              Dec RESULT =null;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		StringLocalizado id = (StringLocalizado)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = (Dec) sem.decType(t, id.str()).ponFila(id.fila()).ponCol(id.col()); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("declaracion",4, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // declaracion ::= tipo IDENTIFICADOR 
            {
              Dec RESULT =null;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		StringLocalizado id = (StringLocalizado)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = (Dec) sem.decType(t, id.str()).ponFila(id.fila()).ponCol(id.col()); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("declaracion",4, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // parametros_formales ::= PARENTESIS_APERTURA lista_parametros_formales_e PARENTESIS_CIERRE 
            {
              ParamForms RESULT =null;
		ParamForms lista = (ParamForms)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		 RESULT = lista; 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("parametros_formales",11, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // lista_parametros_formales_e ::= lista_parametros_formales 
            {
              ParamForms RESULT =null;
		LParams lista = (LParams)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.siParam(lista); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("lista_parametros_formales_e",12, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // lista_parametros_formales_e ::= 
            {
              ParamForms RESULT =null;
		 RESULT = sem.noParam(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("lista_parametros_formales_e",12, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // lista_parametros_formales ::= lista_parametros_formales COMA parametro_formal 
            {
              LParams RESULT =null;
		LParams lista = (LParams)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		ParamForm param = (ParamForm)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.muchosParams(lista, param); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("lista_parametros_formales",13, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // lista_parametros_formales ::= parametro_formal 
            {
              LParams RESULT =null;
		ParamForm param = (ParamForm)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.unParam(param); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("lista_parametros_formales",13, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // parametro_formal ::= tipo REFERENCIA IDENTIFICADOR 
            {
              ParamForm RESULT =null;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		StringLocalizado id = (StringLocalizado)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = (ParamForm) sem.paramFormRef(t, id.str()).ponFila(id.fila()).ponCol(id.col()); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("parametro_formal",16, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // parametro_formal ::= tipo IDENTIFICADOR 
            {
              ParamForm RESULT =null;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		StringLocalizado id = (StringLocalizado)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = (ParamForm) sem.paramForm(t, id.str()).ponFila(id.fila()).ponCol(id.col()); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("parametro_formal",16, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // tipo ::= T0 
            {
              Tipo RESULT =null;
		Tipo t0 = (Tipo)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = t0; 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("tipo",5, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // T0 ::= T0 CORCHETE_APERTURA LITERAL_ENTERO CORCHETE_CIERRE 
            {
              Tipo RESULT =null;
		Tipo t0 = (Tipo)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-3)).value;
		StringLocalizado id = (StringLocalizado)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		 RESULT = (Tipo) sem.tArray(t0, id.str()).ponFila(id.fila()).ponCol(id.col()); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("T0",6, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // T0 ::= T1 
            {
              Tipo RESULT =null;
		Tipo t1 = (Tipo)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = t1; 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("T0",6, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // T1 ::= INDIRECCION T1 
            {
              Tipo RESULT =null;
		Tipo t1 = (Tipo)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.tPunt(t1); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("T1",7, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // T1 ::= T2 
            {
              Tipo RESULT =null;
		Tipo t2 = (Tipo)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = t2; 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("T1",7, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // T2 ::= ID_INT 
            {
              Tipo RESULT =null;
		 RESULT = sem.tInt(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("T2",8, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // T2 ::= ID_REAL 
            {
              Tipo RESULT =null;
		 RESULT = sem.tReal(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("T2",8, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // T2 ::= ID_BOOL 
            {
              Tipo RESULT =null;
		 RESULT = sem.tBool(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("T2",8, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // T2 ::= ID_STRING 
            {
              Tipo RESULT =null;
		 RESULT = sem.tString(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("T2",8, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // T2 ::= IDENTIFICADOR 
            {
              Tipo RESULT =null;
		StringLocalizado id = (StringLocalizado)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = (Tipo) sem.tIden(id.str()).ponFila(id.fila()).ponCol(id.col()); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("T2",8, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // T2 ::= ID_STRUCT LLAVE_APERTURA lista_campos LLAVE_CIERRE 
            {
              Tipo RESULT =null;
		LCampos campos = (LCampos)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		 RESULT = sem.tStruct(campos); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("T2",8, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // lista_campos ::= lista_campos COMA campo 
            {
              LCampos RESULT =null;
		LCampos lista = (LCampos)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		Campo c = (Campo)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.muchosCamps(lista, c); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("lista_campos",28, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // lista_campos ::= campo 
            {
              LCampos RESULT =null;
		Campo c = (Campo)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.unCamp(c); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("lista_campos",28, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // campo ::= tipo IDENTIFICADOR 
            {
              Campo RESULT =null;
		Tipo t = (Tipo)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		StringLocalizado id = (StringLocalizado)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = (Campo) sem.campo(t, id.str()).ponFila(id.fila()).ponCol(id.col()); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("campo",14, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // instrucciones ::= lista_instrucciones 
            {
              Instrs RESULT =null;
		LInstrs lista = (LInstrs)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.siInstrs(lista); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("instrucciones",9, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // instrucciones ::= 
            {
              Instrs RESULT =null;
		 RESULT = sem.noInstrs(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("instrucciones",9, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // lista_instrucciones ::= lista_instrucciones PUNTO_Y_COMA instruccion 
            {
              LInstrs RESULT =null;
		LInstrs lista = (LInstrs)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		Instr instr = (Instr)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.muchasInstrs(lista, instr); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",10, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // lista_instrucciones ::= instruccion 
            {
              LInstrs RESULT =null;
		Instr instr = (Instr)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.unaInstr(instr); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",10, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // instruccion ::= INI_NOMBRE expresion 
            {
              Instr RESULT =null;
		Exp exp = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.arrobaInstr(exp); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("instruccion",15, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // instruccion ::= ID_CALL IDENTIFICADOR parametros_reales 
            {
              Instr RESULT =null;
		StringLocalizado id = (StringLocalizado)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		ParamReales param = (ParamReales)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = (Instr) sem.procInstr(id.str(), param).ponFila(id.fila()).ponCol(id.col()); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("instruccion",15, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // instruccion ::= ID_NL 
            {
              Instr RESULT =null;
		 RESULT = sem.nlInstr(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("instruccion",15, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // instruccion ::= ID_NEW expresion 
            {
              Instr RESULT =null;
		Exp exp = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.newInstr(exp); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("instruccion",15, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // instruccion ::= ID_READ expresion 
            {
              Instr RESULT =null;
		Exp exp = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.readInstr(exp); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("instruccion",15, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // instruccion ::= ID_WRITE expresion 
            {
              Instr RESULT =null;
		Exp exp = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.writeInstr(exp); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("instruccion",15, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // instruccion ::= ID_DELETE expresion 
            {
              Instr RESULT =null;
		Exp exp = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.deleteInstr(exp); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("instruccion",15, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // instruccion ::= ID_WHILE expresion bloque 
            {
              Instr RESULT =null;
		Exp exp = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		Bloque blq = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.whileInstr(exp, blq); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("instruccion",15, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // instruccion ::= ID_IF expresion bloque ID_ELSE bloque 
            {
              Instr RESULT =null;
		Exp exp = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-3)).value;
		Bloque blq = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		Bloque blqh = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.ifElseInstr(exp, blq, blqh); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("instruccion",15, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // instruccion ::= ID_IF expresion bloque 
            {
              Instr RESULT =null;
		Exp exp = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		Bloque blq = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.ifInstr(exp, blq); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("instruccion",15, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // instruccion ::= bloque 
            {
              Instr RESULT =null;
		Bloque blq = (Bloque)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.bloqueInstr(blq); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("instruccion",15, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // parametros_reales ::= PARENTESIS_APERTURA lista_expresiones_e PARENTESIS_CIERRE 
            {
              ParamReales RESULT =null;
		ParamReales lista = (ParamReales)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		 RESULT = lista; 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("parametros_reales",29, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // lista_expresiones_e ::= lista_expresiones 
            {
              ParamReales RESULT =null;
		LExp lista = (LExp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.siExp(lista); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("lista_expresiones_e",30, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // lista_expresiones_e ::= 
            {
              ParamReales RESULT =null;
		 RESULT = sem.noExp(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("lista_expresiones_e",30, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // lista_expresiones ::= lista_expresiones COMA expresion 
            {
              LExp RESULT =null;
		LExp lista = (LExp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		Exp exp = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.muchasExp(lista, exp); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("lista_expresiones",31, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // lista_expresiones ::= expresion 
            {
              LExp RESULT =null;
		Exp exp = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.unaExp(exp); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("lista_expresiones",31, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion ::= E0 
            {
              Exp RESULT =null;
		Exp e0 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = e0; 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("expresion",32, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // E0 ::= E1 ASIGNACION E0 
            {
              Exp RESULT =null;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		Exp e0 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.asignacion(e1, e0); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E0",17, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // E0 ::= E1 
            {
              Exp RESULT =null;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = e1; 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E0",17, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // E1 ::= E1 OP1 E2 
            {
              Exp RESULT =null;
		Exp e1 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		String op = (String)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.mkop1(op, e1, e2); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E1",18, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // E1 ::= E2 
            {
              Exp RESULT =null;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = e2; 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E1",18, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // E2 ::= E2 SUMA E3 
            {
              Exp RESULT =null;
		Exp e2 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		Exp e3 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.suma(e2, e3); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E2",19, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // E2 ::= E3 RESTA E3 
            {
              Exp RESULT =null;
		Exp e3a = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		Exp e3b = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.resta(e3a, e3b); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E2",19, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // E2 ::= E3 
            {
              Exp RESULT =null;
		Exp e3 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = e3; 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E2",19, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // E3 ::= E4 ID_AND E3 
            {
              Exp RESULT =null;
		Exp e4 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		Exp e3 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.and(e4, e3); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E3",20, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // E3 ::= E4 ID_OR E4 
            {
              Exp RESULT =null;
		Exp e41 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		Exp e42 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.or(e41, e42); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E3",20, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // E3 ::= E4 
            {
              Exp RESULT =null;
		Exp e4 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = e4; 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E3",20, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // E4 ::= E4 OP4 E5 
            {
              Exp RESULT =null;
		Exp e4 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		String op = (String)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		Exp e5 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.mkop4(op, e4, e5); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E4",21, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // E4 ::= E5 
            {
              Exp RESULT =null;
		Exp e5 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = e5; 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E4",21, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // E5 ::= OP5 E5 
            {
              Exp RESULT =null;
		String op = (String)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		Exp e5 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = sem.mkop5(op, e5); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E5",22, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // E5 ::= E6 
            {
              Exp RESULT =null;
		Exp e6 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = e6; 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E5",22, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // E6 ::= E6 CORCHETE_APERTURA E0 CORCHETE_CIERRE 
            {
              Exp RESULT =null;
		Exp e6 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-3)).value;
		Exp e0 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		 RESULT = sem.array(e6, e0); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E6",23, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // E6 ::= E6 PUNTO IDENTIFICADOR 
            {
              Exp RESULT =null;
		Exp e6 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-2)).value;
		StringLocalizado id = (StringLocalizado)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = (Exp) sem.expCampo(e6, id.str()).ponFila(id.fila()).ponCol(id.col()); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E6",23, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // E6 ::= E6 INDIRECCION 
            {
              Exp RESULT =null;
		Exp e6 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		 RESULT = sem.punt(e6); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E6",23, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // E6 ::= E7 
            {
              Exp RESULT =null;
		Exp e7 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = e7; 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E6",23, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // E7 ::= LITERAL_REAL 
            {
              Exp RESULT =null;
		StringLocalizado litR = (StringLocalizado)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = (Exp) sem.litReal(litR.str()).ponFila(litR.fila()).ponCol(litR.col()); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E7",24, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // E7 ::= LITERAL_ENTERO 
            {
              Exp RESULT =null;
		StringLocalizado litE = (StringLocalizado)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = (Exp) sem.litEnt(litE.str()).ponFila(litE.fila()).ponCol(litE.col()); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E7",24, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // E7 ::= IDENTIFICADOR 
            {
              Exp RESULT =null;
		StringLocalizado id = (StringLocalizado)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = (Exp) sem.iden(id.str()).ponFila(id.fila()).ponCol(id.col()); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E7",24, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // E7 ::= LITERAL_CADENA 
            {
              Exp RESULT =null;
		StringLocalizado litC = (StringLocalizado)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = (Exp) sem.litCad(litC.str()).ponFila(litC.fila()).ponCol(litC.col()); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E7",24, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // E7 ::= TRUE 
            {
              Exp RESULT =null;
		 RESULT = sem._true(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E7",24, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // E7 ::= FALSE 
            {
              Exp RESULT =null;
		 RESULT = sem._false(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E7",24, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // E7 ::= ID_NULL 
            {
              Exp RESULT =null;
		 RESULT = sem._null(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E7",24, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // E7 ::= PARENTESIS_APERTURA E0 PARENTESIS_CIERRE 
            {
              Exp RESULT =null;
		Exp e0 = (Exp)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.elementAt(CUP$ConstructorASTs$top-1)).value;
		 RESULT = e0; 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("E7",24, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // OP1 ::= MENOR 
            {
              String RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = op.toString(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("OP1",25, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // OP1 ::= MAYOR 
            {
              String RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = op.toString(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("OP1",25, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // OP1 ::= MENOR_IGUAL 
            {
              String RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = op.toString(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("OP1",25, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // OP1 ::= MAYOR_IGUAL 
            {
              String RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = op.toString(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("OP1",25, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // OP1 ::= DESIGUAL 
            {
              String RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = op.toString(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("OP1",25, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // OP1 ::= IGUAL 
            {
              String RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = op.toString(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("OP1",25, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // OP4 ::= MULTIPLICACION 
            {
              String RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = op.toString(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("OP4",26, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // OP4 ::= DIVISION 
            {
              String RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = op.toString(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("OP4",26, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // OP4 ::= MODULO 
            {
              String RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = op.toString(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("OP4",26, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // OP5 ::= RESTA 
            {
              String RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = op.toString(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("OP5",27, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // OP5 ::= ID_NOT 
            {
              String RESULT =null;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$ConstructorASTs$stack.peek()).value;
		 RESULT = op.toString(); 
              CUP$ConstructorASTs$result = parser.getSymbolFactory().newSymbol("OP5",27, RESULT);
            }
          return CUP$ConstructorASTs$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ConstructorASTs$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ConstructorASTs$do_action(
    int                        CUP$ConstructorASTs$act_num,
    java_cup.runtime.lr_parser CUP$ConstructorASTs$parser,
    java.util.Stack            CUP$ConstructorASTs$stack,
    int                        CUP$ConstructorASTs$top)
    throws java.lang.Exception
    {
              return CUP$ConstructorASTs$do_action_part00000000(
                               CUP$ConstructorASTs$act_num,
                               CUP$ConstructorASTs$parser,
                               CUP$ConstructorASTs$stack,
                               CUP$ConstructorASTs$top);
    }
}

