package componentesLexicos;

public enum ClaseLexica {
	SUMA, RESTA, MULTIPLICACION, DIVISION, ID_AND, ID_OR, ID_NOT, ASIGNACION, MENOR, MAYOR, MENOR_IGUAL, MAYOR_IGUAL, DESIGUAL, IGUAL, INT, REAL, ID_BOOL,
	TRUE, FALSE, PARENTESIS_APERTURA, PARENTESIS_CIERRE, LLAVE_APERTURA, LLAVE_CIERRE, PUNTO_Y_COMA, TERMINACION, INI_NOMBRE, LITERAL_ENTERO, 
	LITERAL_REAL, IDENTIFICADOR, EOF, REFERENCIA, ID_REAL, ID_IF, ID_ELSE, ID_NEW, ID_DELETE, ID_TYPE, ID_STRING, MODULO, CORCHETE_APERTURA, CORCHETE_CIERRE,
	PUNTO, ID_NULL, ID_WHILE, ID_READ, ID_CALL, ID_NL
}
