package alex;

public enum Estado {
	INICIO, REC_ID, REC_EXP_0, EXP_SIGNO, REC_EXP, EXPONENCIAL, REC_DECIMAL, _0_DECIMAL, DECIMAL, REC_ENTERO, REC_0_DECIMAL, REC_CERO, REC_MENOS,
	REC_MAS, INI_COMENTARIO, REC_COMENTARIO, REC_PUNTO_COMA, INI_TERMINACION, REC_TERMINACION, REC_NOMBRE, REC_L_CIERRE, REC_L_APERTURA,
	REC_P_CIERRE, REC_P_APERTURA, REC_DISTINTO, EXCLAMACION, REC_MAYOR_IGUAL, REC_MAYOR, REC_MENOR_IGUAL, REC_MENOR, REC_IGUAL_IGUAL, 
	REC_IGUAL, REC_DIV, REC_MUL, REC_EOF
}
