/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package asint_desc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int digitoPositivo = 2;
  /** RegularExpression Id. */
  int digito = 3;
  /** RegularExpression Id. */
  int parteEntera = 4;
  /** RegularExpression Id. */
  int parteDecimal = 5;
  /** RegularExpression Id. */
  int literalEntero = 8;
  /** RegularExpression Id. */
  int literalReal = 9;
  /** RegularExpression Id. */
  int literalCadena = 10;
  /** RegularExpression Id. */
  int int_id = 11;
  /** RegularExpression Id. */
  int real_id = 12;
  /** RegularExpression Id. */
  int bool_id = 13;
  /** RegularExpression Id. */
  int string_id = 14;
  /** RegularExpression Id. */
  int struct_id = 15;
  /** RegularExpression Id. */
  int not_id = 16;
  /** RegularExpression Id. */
  int proc_id = 17;
  /** RegularExpression Id. */
  int type_id = 18;
  /** RegularExpression Id. */
  int if_id = 19;
  /** RegularExpression Id. */
  int call_id = 20;
  /** RegularExpression Id. */
  int nl_id = 21;
  /** RegularExpression Id. */
  int new_id = 22;
  /** RegularExpression Id. */
  int read_id = 23;
  /** RegularExpression Id. */
  int write_id = 24;
  /** RegularExpression Id. */
  int delete_id = 25;
  /** RegularExpression Id. */
  int while_id = 26;
  /** RegularExpression Id. */
  int else_id = 27;
  /** RegularExpression Id. */
  int and_id = 28;
  /** RegularExpression Id. */
  int or_id = 29;
  /** RegularExpression Id. */
  int true_id = 30;
  /** RegularExpression Id. */
  int false_id = 31;
  /** RegularExpression Id. */
  int null_id = 32;
  /** RegularExpression Id. */
  int iden = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<token of kind 6>",
    "<token of kind 7>",
    "<literalEntero>",
    "<literalReal>",
    "<literalCadena>",
    "\"int\"",
    "\"real\"",
    "\"bool\"",
    "\"string\"",
    "\"struct\"",
    "\"not\"",
    "\"proc\"",
    "\"type\"",
    "\"if\"",
    "\"call\"",
    "\"nl\"",
    "\"new\"",
    "\"read\"",
    "\"write\"",
    "\"delete\"",
    "\"while\"",
    "\"else\"",
    "\"and\"",
    "\"or\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<iden>",
    "\"{\"",
    "\"}\"",
    "\"&&\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"[\"",
    "\"]\"",
    "\"^\"",
    "\"@\"",
    "\"=\"",
    "\"-\"",
    "\"+\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\".\"",
  };

}
