
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Mar 04 13:58:05 CET 2024
//----------------------------------------------------

package asint_asc;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int ID_READ = 38;
  public static final int LITERAL_ENTERO = 13;
  public static final int TERMINACION = 2;
  public static final int PARENTESIS_CIERRE = 16;
  public static final int PUNTO_Y_COMA = 4;
  public static final int LITERAL_REAL = 47;
  public static final int ID_PROC = 35;
  public static final int ID_WRITE = 39;
  public static final int RESTA = 27;
  public static final int REFERENCIA = 44;
  public static final int ID_INT = 18;
  public static final int ID_OR = 46;
  public static final int IDENTIFICADOR = 22;
  public static final int IGUAL = 10;
  public static final int CORCHETE_CIERRE = 12;
  public static final int ID_AND = 45;
  public static final int ID_NOT = 31;
  public static final int ID_IF = 33;
  public static final int SUMA = 26;
  public static final int INI_NOMBRE = 32;
  public static final int LITERAL_CADENA = 48;
  public static final int EOF = 0;
  public static final int TRUE = 49;
  public static final int CORCHETE_APERTURA = 11;
  public static final int ID_STRING = 21;
  public static final int error = 1;
  public static final int COMA = 17;
  public static final int MODULO = 30;
  public static final int MENOR = 5;
  public static final int ID_STRUCT = 23;
  public static final int ID_NEW = 41;
  public static final int ID_TYPE = 36;
  public static final int DESIGUAL = 9;
  public static final int ID_BOOL = 20;
  public static final int ASIGNACION = 3;
  public static final int ID_CALL = 37;
  public static final int MAYOR = 6;
  public static final int ID_WHILE = 40;
  public static final int INDIRECCION = 52;
  public static final int ID_NL = 43;
  public static final int PUNTO = 14;
  public static final int LLAVE_APERTURA = 24;
  public static final int MAYOR_IGUAL = 8;
  public static final int LLAVE_CIERRE = 25;
  public static final int ID_NULL = 51;
  public static final int PARENTESIS_APERTURA = 15;
  public static final int MENOR_IGUAL = 7;
  public static final int FALSE = 50;
  public static final int ID_DELETE = 42;
  public static final int DIVISION = 29;
  public static final int ID_REAL = 19;
  public static final int MULTIPLICACION = 28;
  public static final int ID_ELSE = 34;
}

