
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 05 21:58:10 CEST 2024
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int ID_READ = 35;
  public static final int LITERAL_ENTERO = 47;
  public static final int TERMINACION = 2;
  public static final int PARENTESIS_CIERRE = 14;
  public static final int PUNTO_Y_COMA = 4;
  public static final int LITERAL_REAL = 49;
  public static final int ID_PROC = 32;
  public static final int ID_WRITE = 36;
  public static final int RESTA = 24;
  public static final int REFERENCIA = 41;
  public static final int ID_INT = 16;
  public static final int ID_OR = 43;
  public static final int IDENTIFICADOR = 48;
  public static final int IGUAL = 10;
  public static final int CORCHETE_CIERRE = 11;
  public static final int ID_AND = 42;
  public static final int ID_NOT = 28;
  public static final int ID_IF = 30;
  public static final int SUMA = 23;
  public static final int INI_NOMBRE = 29;
  public static final int LITERAL_CADENA = 50;
  public static final int EOF = 0;
  public static final int CORCHETE_APERTURA = 52;
  public static final int TRUE = 44;
  public static final int ID_STRING = 19;
  public static final int error = 1;
  public static final int COMA = 15;
  public static final int MODULO = 27;
  public static final int MENOR = 5;
  public static final int ID_STRUCT = 20;
  public static final int ID_NEW = 38;
  public static final int ID_TYPE = 33;
  public static final int DESIGUAL = 9;
  public static final int ID_BOOL = 18;
  public static final int ASIGNACION = 3;
  public static final int MAYOR = 6;
  public static final int ID_CALL = 34;
  public static final int ID_WHILE = 37;
  public static final int INDIRECCION = 51;
  public static final int ID_NL = 40;
  public static final int PUNTO = 12;
  public static final int LLAVE_APERTURA = 21;
  public static final int MAYOR_IGUAL = 8;
  public static final int LLAVE_CIERRE = 22;
  public static final int ID_NULL = 46;
  public static final int PARENTESIS_APERTURA = 13;
  public static final int MENOR_IGUAL = 7;
  public static final int FALSE = 45;
  public static final int ID_DELETE = 39;
  public static final int DIVISION = 26;
  public static final int ID_REAL = 17;
  public static final int MULTIPLICACION = 25;
  public static final int ID_ELSE = 31;
}

