package componentesLexicos;

public enum ClaseLexica {
	IDENTIFICADOR, LITERAL_ENTERO, LITERAL_REAL, INT, REAL, BOOL, TRUE, FALSE, PARENTESIS_APERTURA,
	PARENTESIS_CIERRE, SUMA, RESTA, MULTIPLICACION, DIVISION, ASIGNACION, MENOR, MENOR_IGUAL,
	MAYOR, MAYOR_IGUAL, IGUAL, DESIGUAL, EOF
}
