package componentesLexicos;

public enum ClaseLexica {
	SUMA, RESTA, MULTIPLICACION, DIVISION, AND, OR, NOT, ASIGNACION, MENOR, MAYOR, MENOR_IGUAL, MAYOR_IGUAL, DESIGUAL, IGUAL, INT, REAL, BOOL,
	TRUE, FALSE, PARENTESIS_APERTURA, PARENTESIS_CIERRE, LLAVE_APERTURA, LLAVE_CIERRE, PUNTO_Y_COMA, TERMINACION, INI_NOMBRE, LITERAL_ENTERO, 
	LITERAL_REAL, IDENTIFICADOR
}
